version: '3.1'
services:
  php:
    build: .
    image: dsafetech
    ports:
      - $PHP_PORT:80
    volumes:
      - .:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=-1
  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - SQL_MODE=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      - TZ=America/Sao_Paulo
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - $PMA_PORT:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=1G
volumes:
  db:
